version: "3.5"

x-logging:
  &default-logging
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "2"

networks:
  backbone-net:
    name: backbone-net

services:
  nginx-controller:
    container_name: nginx-controller
    image: nginx:1.17.8
    logging: *default-logging
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl.d:/ssl.d:ro
      - ./webroot.d:/webroot.d:ro
      - certs:/etc/letsencrypt:ro
      - certs-data:/data/letsencrypt:ro
    networks:
      - backbone-net
    ports:
      - 80:80
      - 443:443

